<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset 
  name CDATA #REQUIRED
  levels CDATA #IMPLIED  
  span CDATA #IMPLIED
  level CDATA #IMPLIED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
 <!ENTITY layer_real_source_path "/sf/os/mmaudio" >
]>
<SystemDefinition name="os_mmaudio_pkg" schema="1.4.0">
	<systemModel>
  <!-- Common file for prebuild layers-->
  	<layer name="os_layer">		
			<module name="mmaudio_devsound">
				<unit name="a3facf" unitID="sos.a3facf" mrp="" bldFile="&layer_real_source_path;/devsound/a3facf/group"/>				
				<unit name="a3fdevsound" unitID="sos.a3fdevsound" mrp="" bldFile="&layer_real_source_path;/devsound/a3fdevsound/group"/>				
				<unit name="a3ftrace" unitID="sos.a3ftrace" mrp="" bldFile="&layer_real_source_path;/devsound/a3ftrace/group"/>
				<unit name="hwdevapi" unitID="sos.hwdevapi" mrp="" bldFile="&layer_real_source_path;/devsound/hwdevapi/group"/>				
				<unit name="devsoundapi" unitID="sos.devsoundapi" mrp="" bldFile="&layer_real_source_path;/devsound/devsoundapi/group"/>
			</module>			
			<module name="mmaudio_mmlibs">
				<unit name="mmutilitylib" unitID="sos.mmutilitylib" mrp="" bldFile="&layer_real_source_path;/mmlibs/mmutilitylib/group"/>
				<unit name="mmfw" unitID="sos.mmfw" mrp="" bldFile="&layer_real_source_path;/mmlibs/mmfw/group"/>
				<unit name="mmfcodecs" unitID="sos.mmfcodecs" mrp="" bldFile="&layer_real_source_path;/mmlibs/mmfw/codecs/group"/>				
			</module>			
			<module name="mmaudio_pub">
				<unit name="mmaudio_pub" unitID="sos.mmaudio_pub" mrp="" bldFile="&layer_real_source_path;/mmaudio_pub/group"/>
			</module>
			<module name="mmaudio_plat">
				<unit name="mmaudio_plat" unitID="sos.mmaudio_plat" mrp="" bldFile="&layer_real_source_path;/mmaudio_plat/group"/>
			</module>
			<module name="mmaudio_devsoundext">
				<unit name="devsoundext" unitID="sos.devsoundext" mrp="" bldFile="&layer_real_source_path;/devsoundextensions/group"/>
			</module>
			<module name="mmaudio_mmplugin">
				<unit name="mmplugin" unitID="sos.mmplugin" mrp="" bldFile="&layer_real_source_path;/mmplugins/mmfwplugins/group"/>
			</module>
			<module name="mmaudio_mmdevicefwspeech">
				<unit name="mmdevicefwspeech" unitID="sos.mmdevicefwspeech" mrp="" bldFile="&layer_real_source_path;/mmdevicefw/speechrecogsupport/group"/>
			</module>
	</layer>
  	<layer name="audio_test_layer">
			<module name="mf_multimedia_test_component">				
				<unit name="mmtestfw" unitID="sos.mmtestfw" bldFile="&layer_real_source_path;/mmtestenv/mmtestfw/group" mrp=""/>
				<unit name="a3fchartest" unitID="sos.a3fchartest" bldFile="&layer_real_source_path;/devsound/a3fcharacterisationtest/group" mrp=""/>
				<unit name="mmfintgdevsound" unitID="sos.mmfintgdevsound" bldFile="&layer_real_source_path;/mmlibs/mmfw/tsrc/mmfintegrationtest/devsound/group" mrp=""/>				
				<!--unit name="SbcCodec" unitID="sos.SbcCodec" bldFile="&layer_real_source_path;/mmlibs/mmfw/tsrc/mmfunittest/SbcCodec/group" mrp=""/-->
				<unit name="mmtestfwunittest" unitID="sos.mmtestfwunittest" bldFile="&layer_real_source_path;/mmtestenv/mmtestfwunittest/group" mrp=""/>
				<unit name="SDevSound" unitID="sos.SDevSound" bldFile="&layer_real_source_path;/mmlibs/mmfw/tsrc/mmfintegrationtest/SDevSound/group" mrp=""/>
				<unit name="DevSoundTest" unitID="sos.DevSoundTest" bldFile="&layer_real_source_path;/mmlibs/mmfw/tsrc/mmfunittest/DevSoundTest/group" mrp=""/>
				<unit name="a3fintegrationtest" unitID="sos.a3fintegrationtest" bldFile="&layer_real_source_path;/devsound/a3fintegrationtest/group" mrp="" />
				<unit name="speechrecogsupporttest" unitID="sos.speechrecogsupporttest" bldFile="&layer_real_source_path;/mmdevicefw/speechrecogsupport/tsrc/ASR/group" mrp=""/>			
			</module>
	</layer>   		
  </systemModel>
</SystemDefinition>
